name: Latest blog posts

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update blog post list
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://takbirhimu.me/rss.xml"
          max_post_count: "3"
          template: '<p align="center"><a href="$url"><img src="https://img.shields.io/badge/READ_ARTICLE-0B0B12?style=for-the-badge" alt="Read article"/></a><br/>📝 <b><a href="$url">$title</a></b><br/><sub>📅 $date</sub></p>$newline'
          date_format: "UTC:mmm dd, yyyy"
